### ISSUE TITLE
htaccess杀爬虫的问题

### ISSUE THREAD

**Issue by oliver661** [netputer/netputweets#14]
用在一个公共SSL虚拟空间中时碰到的问题
不用https的时候没问题
用https的时候 htaccess修改为如下

RewriteBase /[path]/
IndexIgnore *
Options -Indexes
Options +FollowSymlinks
RewriteEngine on
RewriteCond %{HTTP_USER_AGENT} (bot|spider|search|soso|bing|sogou|yahoo|yodao|robozilla) [NC]
RewriteRule ^(.*)$ - [L,R=404]
[之后省略]

运行报RewriteRule: invalid HTTP response code for flag 'R'
我根据 http://www.zoneself.org/2012/03/01/content_928.html 这里的提示改成了

RewriteRule ^(.*)$ https://%{SERVER_NAME} [R=301,L]

就没问题了
但是不知道原因出在哪里

**Comment by oliver661** [comment]
想了一下 改成了 RewriteRule ^(.*)$ http://127.0.0.1/ [R=301,L]

**Comment by shadowglen** [comment]
蛤蛤蛤蛤这个改得好猥琐!!!

**Comment by oliver661** [comment]
面对蜘蛛不能手下留情= w=
404不成咱就只能127.0.0.1的301跳了orz
