### ISSUE TITLE
桌面模式下头像覆盖了部分文字区域

### ISSUE THREAD

**Issue by oliver661** [netputer/netputweets#23]
修正 \common\twitter.php

1385:  $class .= ' shift';
为
1385:  $class .= ' shift48';

**Comment by oliver661** [comment]
这个修正方法会导致所有模式下头像都变成48x48的。。。
还是得奶瓶来改吧/__\

**Comment by netputer** [comment]
页面布局方面后面得大改，现在用的是绝对定位，不靠谱……
—
