### ISSUE TITLE
htaccess注释补充

### ISSUE THREAD

**Issue by oliver661** [netputer/netputweets#24]
主目录下的htaccess注释建议加入如下内容

**Comment by shadowglen** [comment]
那个 你可以fork一个repo然后提交commit~

**Comment by oliver661** [comment]
小修小补 也不是啥大bug 我就不折腾了。。。(其实还是担心改得不对咳)

**Comment by shadowglen** [comment]
那你等奶瓶自己去改吧…

**Comment by netputer** [comment]
其实……这样写有何作用？

**Comment by oliver661** [comment]
我的情况是
如果不这样改htaccess 客户端放在目录里开ssl itap的验证会跳404错误

具体是这样
比如客户端放在/a/t/ 那么客户端主目录里面的htaccess改成
RewriteBase /a/t/
然后把下面的https的301跳的注释号删掉

但是itap代理的时候会出现404错误
也算是误打误撞吧 把oauthproxy目录里的htaccess
加上 RewriteBase /a/t/oauthproxy/
就可以正常代理登录了

我两台支持ssl的主机全都是这么改的……所以觉得应该不是个例了

**Comment by netputer** [comment]
如果不指定 RewriteBase 就不能用了是嘛？

大概懂了，应该把 `/oauthproxy/.htaccess` 合并至 `/.htaccess` ，会减少很多问题。

**Comment by oliver661** [comment]
嗯嗯 不过我倒是觉得oauthproxy用的频率不高 没必要在那里多下工夫 所以提出直接加个修改注释的意见

2013/3/6 NetPuter notifications@github.com
