### ISSUE TITLE
HTTPS自动判断无效

### ISSUE THREAD

**Issue by AstroProfundis** [netputer/netputweets#25]
在 `config.php` 中的第二行不能保证正确判断链接是否为https:

```
$base_url = isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] != "off" ? "https" : "http"; 
```

例如，在appfog上架设时，则总是判断为普通http链接，因为appfog上`$_SERVER["HTTPS"]`总是为空，若上传如下代码：

```
<?php
    echo $_SERVER["HTTPS"];
?>
```

则打开为空白页面。

建议更改为类似embr等网页端的，直接由用户定义完整 `base_url` 的方式。

**Comment by shadowglen** [comment]
HTTPS判断无效是因为你没有在nginx的站点配置文件里
location ~ .*.(php|php5)?${…} 中加入 fastcgi_param HTTPS on;

当然apache肯定也有类似的地方 你可以去查查

**Comment by AstroProfundis** [comment]
appfog 不能自己修改配置的...只能自己设置环境变量，但这个是web服务器给出来的值所以...用户改不了...

**Comment by shadowglen** [comment]
其实原版dabr是有BASE_URL设置的 但为了减少复杂度就自动化了
你可以去config.php里强制把BASE_URL写死

**Comment by AstroProfundis** [comment]
其实我就是说像原版那样写死...

按我说的话大概就是这样... https://github.com/AstroProfundis/netputweets/tree/issue-25

考虑到有能力/权限自己控制服务器配置的用户应该不多...

**Comment by shadowglen** [comment]
我觉得还可以在setup.php里加个选项 自动配置或者手动设定BASE_URL

**Comment by AstroProfundis** [comment]
这个可以有...

**Comment by shadowglen** [comment]
你去改吧… 咳咳…

**Comment by AstroProfundis** [comment]
看了下，不会(﹁"﹁)

**Comment by shadowglen** [comment]
喂喂喂 你节操呢?!

**Comment by DrayChou** [comment]
不会可以学啊，又不难

2013/3/6 Shadowglen Elf notifications@github.com

> 喂喂喂 你节操呢?!
>

**Comment by littleben** [comment]
我的是 apache，第一次安装后从 https 跳转到 http，然后报错（我把 80 端口掐了）。
改了半天自动判断和 BASE_URL，都不行（因为不会）- -
后来再装一遍，神奇地好了...

**Comment by netputer** [comment]
@shadowglen 提供的解决方案能否在 dabr.conf 中实现？

**Comment by shadowglen** [comment]
最好不要这么做 因为这个其实是php相关而非站点相关的
所以在readme里写清楚即可

**Comment by netputer** [comment]
但是这样做足够简单，但用户添加个 `dabr.conf` 的同时还要修改 `nginx.conf`(?) 略复杂……

**Comment by shadowglen** [comment]
实际上是那个域在标准的站点配置文件里有 所以我不确定如果我在dabr.conf里加入会不会有什么不良后果
我去试试先

**Comment by netputer** [comment]
辛苦了。看看在配置文件中已存在或不存在 `fastcgi_param HTTPS on` 的情况下，在 `dabr.conf` 中加入此句是否会造成冲突。

**Comment by shadowglen** [comment]
在dabr中加入那句会导致配置文件中的fastcgi设置被覆盖掉
所以最好不要这么做

**Comment by AstroProfundis** [comment]
我的意思是，对于虚拟主机的用户，是没有权限更改web服务器的配置的，所以应该考虑从奶瓶腿程序本身来解决

**Comment by netputer** [comment]
多方面下手嘛，接下来会通过改进安装程序解决。

**Comment by comicchang** [comment]
如果能修改web服务器配置的话直接改sites-enabled里面相应站点配置文件就可以了，不需要动dabr.conf

如果不能改的话，从一开始就不能include dabr.conf，所以改它也木有用

**Comment by shadowglen** [comment]
我这边表示 除非整个地接管了fastcgi的配置 否则无法单独自动插入一行

**Comment by AstroProfundis** [comment]
嗯嗯，我的意见是在安装程序里面加上一个是否启用 https 链接的选项，然后在 `config.php`
里面直接把链接类型写死，也就是类似我前面放出来的那个 branch 的样子。
