### ISSUE TITLE
发布 Tweet 时出现错误 Error: Invalid HTTP request method for this action.

### ISSUE THREAD

**Issue by scavin** [netputer/netputweets#26]
新版本在测试发布 Tweet 时出现错误提示

 Error: Invalid HTTP request method for this action.

这是服务器的问题还是软件的问题呢?

**Comment by AstroProfundis** [comment]
这个我也遇到过，出现错误提示过后推文实际上是发出去了的（在普通发推和进行官方RT都出现过这个问题）

**Comment by netputer** [comment]
出现这个错误的原因是，发消息时没有用到 POST 方法，并非代码的原因，主要检查服务器配置是否正确（如 Nginx 的 conf ）。刚才帮青蛙解决了。

**Comment by scavin** [comment]
git pull 了一次后又出现问题，最终的解决方案是将 config 文件里的 base_url 三行删除，并添加
define('BASE_URL', 'https://xxx/');
define('BASE_URF', 'https://xxx');

再没有出现问题...

**Comment by shadowglen** [comment]
这个原因是你没在php fastcgi里面把HTTPS打开 导致$_SERVER['HTTPS']为空

**Comment by scavin** [comment]
这个在 nginx 下如何打开？

**Comment by shadowglen** [comment]
你看issue 25 我在里面写了

**Comment by scavin** [comment]
果然是这样的，搞定了。感谢
