### ISSUE TITLE
图标的相对地址bug

### ISSUE THREAD

**Issue by shadowglen** [netputer/netputweets#36]
相对地址这里有个bug:
把图标按钮的选项打开后 所有非index页面上的按钮图标都会死掉

比如user页面里的reply按钮 它的src是"images/reply.png"
正常情况下是被解析成"xxx.com/images/reply.png" 但这里会被解析成"xxx.com/user/images/reply.png" 导致错误
我不知道这是我safari的问题 还是服务器代码的问题...

**Comment by comicchang** [comment]
本来就应该这样。。源代码改成BASE_URL."images/reply.png" 大概就好了
