### ISSUE TITLE
升级到使用is_https()的版本后图片代理失效

### ISSUE THREAD

**Issue by wxt2005** [netputer/netputweets#39]
升级到009286e9f4并重新生成config.php后发现只要打开图片代理，页面内所有img.php?u=xxxx的图片都显示为500错误。
尝试将config.php中的'$base_url = is_https() ? "https" : "http";'注释掉并手动填写BASE_URL后图片显示恢复正常。

**Comment by shadowglen** [comment]
我快崩溃了 怎么还是到处都有base_url错误

**Comment by shadowglen** [comment]
@wxt2005 麻烦你把自己机器的http和ssl情况说一下

**Comment by wxt2005** [comment]
@shadowglen Apache 2.2.16 + PHP 5.3.3-7, 启用了SSL。哦对了，是安装在二级目录下的。

**Comment by shadowglen** [comment]
@wxt2005 要不... 你升级到... 最新版 试试看?

**Comment by wxt2005** [comment]
@shadowglen 你是指apache吗？奶瓶腿最新的还是有这问题（

**Comment by shadowglen** [comment]
@wxt2005 晕了 是所有图都挂了么?

**Comment by chenshaoju** [comment]
能否贴一下Apache的error_log？

**Comment by wxt2005** [comment]
@shadowglen 全挂了。
@chenshaoju 你不说我都忘了……

[Sun Mar 10 20:39:51 2013] [error] [client x.x.x.x] PHP Fatal error:  Call to undefined function is_https() in /npt/config.php on line 3

貌似全是这个错误。难道跟我apache或者php的配置有关系？

**Comment by netputer** [comment]
瞬间明白了……晚点儿看看！

2013/3/10 wxt2005 notifications@github.com

> @shadowglen https://github.com/shadowglen 全挂了。
> @chenshaoju https://github.com/chenshaoju 你不说我都忘了……
> 
> [Sun Mar 10 20:39:51 2013] [error] [client x.x.x.x] PHP Fatal error: Call
> to undefined function is_https() in /npt/config.php on line 3
> 
> 貌似全是这个错误。难道跟我apache或者php的配置有关系？
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/39#issuecomment-14680713
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/

**Comment by shadowglen** [comment]
我也秒懂!

**Comment by shadowglen** [comment]
要不 is_https扔config.php吧... 然后每个页面都require_once('config.php');

**Comment by netputer** [comment]
嗯，这是最简单的方法啦。 `setup.php` 里也能少一个函数。

2013/3/10 Shadowglen Elf notifications@github.com

> 要不 is_https扔config.php吧... 然后每个页面都require_once('config.php');
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/39#issuecomment-14680940
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/

**Comment by shadowglen** [comment]
那个少不了 因为setup.php运行的时候还没config.php

**Comment by netputer** [comment]
噗，瞬间又二了。

2013/3/10 Shadowglen Elf notifications@github.com

> 那个少不了 因为setup.php运行的时候还没config.php
> 
> On Mar 10, 2013, at 8:58 PM, NetPuter notifications@github.com wrote:
> 
> > 嗯，这是最简单的方法啦。 `setup.php` 里也能少一个函数。
> > 
> > 2013/3/10 Shadowglen Elf notifications@github.com
> > 
> > > 要不 is_https扔config.php吧... 然后每个页面都require_once('config.php');
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/netputer/netputweets/issues/39#issuecomment-14680940>
> > > .
> > 
> > ## 
> > 
> > Best Regards,
> > NetPuter Lin _»_ http://netputer.me/
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/39#issuecomment-14680972
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/
