### ISSUE TITLE
IMGPROXY 图片无法显示

### ISSUE THREAD

**Issue by sorz** [netputer/netputweets#4]
开启图片代理后，返回的图片均报错“Notice: Use of undefined constant IMGPROXY ...”。
我不懂PHP，按字面意思在 img.php 里加入 require 'config.php'; 后解决…

之前用的都好好的，也不知道为什么突然冒出了这么个问题…

**Comment by chenshaoju** [comment]
c3acd8f424版本也有这个现象，Apache日志里不断出现以下内容，但是不影响使用，图片也能正常显示。
[Wed Feb 27 11:36:19 2013] [warn] [client 117.85.xxx.xxx] mod_fcgid: stderr: PHP Notice:  Use of undefined constant IMGPROXY - assumed 'IMGPROXY' in /var/www/html/np/img.php on line 25, referer: https://xxx.com/np

**Comment by chenshaoju** [comment]
已经测试，在1147d26bc3或其他版本中该问题已经修正。
