### ISSUE TITLE
incorrect hashtag linking

### ISSUE THREAD

**Issue by yoursunny** [netputer/netputweets#42]
In tweet https://twitter.com/Sun_Tran_Alerts/status/313342549962149888
the hashtag is `#BusDriverAppreciationDay`.

https://t.orzdream.com/status/313342549962149888
displays the tweet as [#BusDriverAppreciatio](https://t.orzdream.com/hash/BusDriverAppreciatio)nDay

**Comment by comicchang** [comment]
https://github.com/netputer/netputweets/blob/master/common/class.regex.php#L98-L103

现在hashtag最多20个字符……

**Comment by shadowglen** [comment]
改了一下regex提交上去了 (其实应该读entities的... 不过... 有空再折腾吧
