### ISSUE TITLE
提示：服务器不支持 URL Rewrite，手动修改config.php，能打开主页，无法登陆使用

### ISSUE THREAD

**Issue by littleben** [netputer/netputweets#45]
提示：服务器不支持 URL Rewrite，手动修改 config.php，能打开主页，无法登陆使用。
搭建在 CE2 上，点击登陆后，显示「Not Found

The requested URL /d/itap was not found on this server.

Apache/2.2.22 (Amazon)  Port 443」

不知道是怎么回事，求教...

ps.同一个服务器上，之前一个旧版的奶瓶腿使用正常。

**Comment by shadowglen** [comment]
不支持rewrite 就... 还是算了吧

**Comment by littleben** [comment]
之前的版本不是也需要  URL Rewrite 的支持么（前一两个月的版本），旧的能使用，说明  URL Rewrite 应该没问题的啊。
ps.如果记错了，肿么开启  URL Rewrite - -

**Comment by shadowglen** [comment]
apache还是nginx?

**Comment by littleben** [comment]
「Apache/2.2.22 (Amazon) Server 」

**Comment by shadowglen** [comment]
等奶瓶吧 我不会玩阿帕奇

**Comment by littleben** [comment]
试过用 service httpd restart 命令重启 http 服务了- -

**Comment by littleben** [comment]
额，好吧，Thx anyway

**Comment by netputer** [comment]
前一两个月的版本能用？奶瓶腿很久之前就放弃了不支持 URL Rewrite 的服务器。

不过一直以来也能看到在 Aws 的架设的教程，所以可能是你的配置问题吧。

**Comment by littleben** [comment]
奶瓶腿在 Aws 上用了一年多，装了好多次，最近的一次是一个月前，都能用的说- -
第一次碰到提示 URL Rewrite 的问题。
试着改了 config.php 里的 base_url，改成固定的，也是不行的 @-@

**Comment by netputer** [comment]
既然如此，那请看看以下几个网址能否访问：

http://yourdomain/yourfolder/settings
http://yourdomain/yourfolder/oauth
http://yourdomain/yourfolder/itap

2013/3/24 littleben notifications@github.com

> 奶瓶腿在 Aws 上用了一年多，装了好多次，最近的一次是一个月前，都能用的说- -
> 第一次碰到提示 URL Rewrite 的问题。
> 试着改了 config.php 里的 base_url，改成固定的，也是不行的 @-@
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/45#issuecomment-15351246
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/

**Comment by littleben** [comment]
额，都不行。有可能是什么原因呢？

**Comment by netputer** [comment]
要么就是你的 Apache 不支持 URL Rewrite 或者配置错误，要么就是 .htaccess 因为某种原因出错了。

前者无法帮你，需要你自己仔细检查……后者试试彻底重装吧。

On Sun, Mar 24, 2013 at 12:32 PM, littleben notifications@github.comwrote:

> 额，都不行。有可能是什么原因呢？
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/45#issuecomment-15351356
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/

**Comment by littleben** [comment]
nice，之前解压的时候，不知怎么丢掉了 .htaccess，因为是 SSL 的，修改了其中三行传上去，重新拥抱奶瓶腿啦~~
hoho ^O^
多谢~

**Comment by shadowglen** [comment]
这...

**Comment by netputer** [comment]
建议使用 Git 方式，升级更方便~

On Sun, Mar 24, 2013 at 12:48 PM, littleben notifications@github.comwrote:

> nice，之前解压的时候，不知怎么丢掉了 .htaccess，因为是 SSL 的，修改了其中三行传上去，重新拥抱奶瓶腿啦~~
> hoho ^O^
> 多谢~
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/45#issuecomment-15351464
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/

**Comment by wujun4code** [comment]
我目前也遇到这种情况，我用的是windows azure的云虚拟机，虚拟的ubuntu server 系统。
1.我确定我的apache2 开启了 sudo a2enmod rewrite，我也把配置文件中的改成了AllowOverride All，并且sudo service apache2 restart，但是还是粗线这样的问题……
2.url rewrite 这个模块是需要服务器本身的机器支持的还是ubuntu 系统支持？本屌是ubuntu新手，见笑见笑。

**Comment by netputer** [comment]
方便的话把地址发给我看看……

2013/10/14 freewing99 notifications@github.com

> 我目前也遇到这种情况，我用的是windows azure的云虚拟机，虚拟的ubuntu server 系统。
> 1.我确定我的apache2 开启了 sudo a2enmod rewrite，我也把配置文件中的改成了AllowOverride
> All，并且sudo service apache2 restart，但是还是粗线这样的问题……
> 2.url rewrite 这个模块是需要服务器本身的机器支持的还是ubuntu 系统支持？本屌是ubuntu新手，见笑见笑。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/45#issuecomment-26256263
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/
