### ISSUE TITLE
转义符bug

### ISSUE THREAD

**Issue by oliver661** [netputer/netputweets#46]
FF浏览器下发推

测试 转义符bug " \ ^ ` ~ . / ,
'

会变成 

测试 转义符bug \" \ ^ ` ~ . / ,
\'

**Comment by netputer** [comment]
确定是使用的最新奶瓶腿吗？我自己测试没有这个问题。

On Tue, Apr 2, 2013 at 9:04 AM, OliverM. notifications@github.com wrote:

> FF浏览器下发推
> 
> 测试 转义符bug " \ ^ ` ~ . / ,
> '
> 
> 会变成
> 
> 测试 转义符bug \" \ ^ ` ~ . / ,
> \'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/46
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/

**Comment by oliver661** [comment]
是的 最新下了 直接把原来删了的 请问这个问题是在哪里修正的?
我怀疑是不是和主机有关= =

**Comment by netputer** [comment]
应该是
https://github.com/netputer/netputweets/commit/7217b857d06e964ebc71311b4feee7de702f4d4e

2013/4/6 OliverM. notifications@github.com

> 是的 最新下了 直接把原来删了的 请问这个问题是在哪里修正的?
> 我怀疑是不是和主机有关= =
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/46#issuecomment-15997392
> .

## 

Best Regards,
NetPuter Lin _»_ http://netputer.me/

**Comment by oliver661** [comment]
是的 是这样的 所以我也有点奇怪= =

2013/4/6 NetPuter notifications@github.com

**Comment by netputer** [comment]
刚想起来，确实有可能是因为服务器开启了 POST 过滤之类的选项，具体叫啥不清楚……

发自我的 iPhone

在 2013-4-7，0:30，"OliverM." notifications@github.com 写道：

是的 是这样的 所以我也有点奇怪= =

2013/4/6 NetPuter notifications@github.com

> 应该是
> 
> https://github.com/netputer/netputweets/commit/7217b857d06e964ebc71311b4feee7de702f4d4e
> 
> 2013/4/6 OliverM. notifications@github.com
> 
> > 是的 最新下了 直接把原来删了的 请问这个问题是在哪里修正的?
> > 我怀疑是不是和主机有关= =
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/netputer/netputweets/issues/46#issuecomment-15997392>
> > .
> 
> ## 
> 
> Best Regards,
> NetPuter Lin _»_ http://netputer.me/
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/netputer/netputweets/issues/46#issuecomment-15997699>
> .

—
Reply to this email directly or view it on
GitHubhttps://github.com/netputer/netputweets/issues/46#issuecomment-15999137
.

**Comment by oliver661** [comment]
这样……那我换另外一个主机再试试…………等国内早上的时候再汇报情况吧

2013/4/6 NetPuter notifications@github.com

**Comment by oliver661** [comment]
两个都不行 我爬了爬文章 说是magic_quotes_gpc设为on了
解决办法是引用 stripslashes函数 http://cn2.php.net/stripslashes

以上为爬文结果>___<
