### ISSUE TITLE
代理登录报403错误

### ISSUE THREAD

**Issue by lordong** [netputer/netputweets#47]
打开https://t.orzdream.com/，点Proxy链接登录，输入正确的用户名和密码点Sign In，立即报错：403 Forbidden: The server understood the request, but is refusing to fulfill it. 此时的网址是：https://t.orzdream.com/oauthproxy/authorize_post (见附图)

如果点Sign In with Twitter OAuth链接使用官方认证则正常。

自建的奶瓶腿也出现这个问题，以前成功通过代理登录没有退出的仍可正常使用。换另外的帐号也如此。

![netputer](https://f.cloud.github.com/assets/4092817/351466/9acb44cc-a04a-11e2-8fbf-0b4cf83a403d.png)

**Comment by lordong** [comment]
以前代理登录没有问题，应该是最近的事，我自建的奶瓶腿使用nginx所以用不到.htaccess的配置，怀疑跟Twitter修改什么了东东有关

**Comment by netputer** [comment]
@lordong 那有没有更新 Nginx 配置？

**Comment by lordong** [comment]
我没有更新过Nginx的配置，同时我试了以前建的奶瓶腿老版本，代理登录时也是一样的403错误。

**Comment by laoyang945** [comment]
同样的错误，自建奶瓶腿，apache
embr也无法通过代理进行认证了
不知道是不是twitter政策修改

**Comment by wangym5106** [comment]
自建奶瓶腿昨天也是这个问题，今天已经恢复正常，应该是twitter的API接口出了问题。

**Comment by netputer** [comment]
嗯嗯，我的也恢复正常了，各位看看。

**Comment by lordong** [comment]
目前都正常了，应该是Twitter修复了某个Bug，关贴
