### ISSUE TITLE
最近经常碰到stdClass错误

### ISSUE THREAD

**Issue by lordong** [netputer/netputweets#48]
Fatal error: Cannot use object of type stdClass as array in common/class.embedly.php on line 72

通常是在登录成功后，不知道是不是跟Twitter间歇性休克有关系，没做什么修改过一阵子就自动好了

**Comment by netputer** [comment]
暂时不太清楚问题在哪里。

如果下次再次出现这个问题，请将该页面另存为，或者将包含图片的推文 ID 贴上来。

**Comment by shadowglen** [comment]
那个啊 好像是embedly的问题
看看embedly key是不是对的...

**Comment by lordong** [comment]
我之前出错的页面没关掉，通过你的站点总算被我找到出错的ID了：https://t.orzdream.com/status/329803487430979584

在你的站点没有问题，但在我自己建的站加载这个ID的图片就报上面这个错误，我下载部署的版本时间是北京时间2013-2-27 20:35，图片相关配置项（KEY是默认的）：
define("EMBEDLY_KEY", "95a105b0faadab9daa1a5739d4f80992");

define("BASE_URL", $base_url);

define("NPT_TITLE", "奶瓶腿!");
define("API_ROOT", "https://api.twitter.com/1.1/");
define("LANG", "zh_CN");

define("IMGPROXY", 1);
define("IMGPROXY_THUMB", 1);

**Comment by lordong** [comment]
又逮到一枚出错的ID: https://t.orzdream.com/status/330213695554723840
发现这些图都是来自 www.flickr.com 的图床，可能跟IMGPROXY有关系。

**Comment by netputer** [comment]
感谢。这个问题和 Embedly 有关。

**Comment by lordong** [comment]
做了点修改，把 common/class.embedly.php 第65行的key参数去掉就好了，然后在第75行之前插一句 $url = urldecode($url); 就可以显示正确的URL，可能现在不用key了

**Comment by shadowglen** [comment]
commit plz

**Comment by lordong** [comment]
修改的代码段（common/class.embedly.php 第65行开始）：
    $url = 'http://api.embed.ly/1/oembed?urls=' . implode(',', $justUrls) . '&format=json';

```
$embedly_json = twitter_fetch($url);
$oembeds = json_decode($embedly_json);

// Put the thumbnails into the $feed
foreach ($justUrls as $index => $url) {
    if ($thumb = $oembeds[$index]->thumbnail_url) {
        foreach ($matched_urls[$url] as $statusId) {
            $url = urldecode($url);
            $feed[$statusId]->text .= "<br /><a href=\"$url\"><img src=\"".img_proxy_url($thumb)."\" style=\"max-width:150px;\" /></a>";
        }
    }
}
```

Dropbox共享链接：http://db.tt/rzrqDQyr

**Comment by shadowglen** [comment]
@lordong embedly的api docs表示key是必须的

**Comment by lordong** [comment]
@shadowglen embedly的api docs我没有细看，只不过我在测试时用 @netputer 提供的95a105b0faadab9daa1a5739d4f80992这个Key去获取内容时显示无效的Key，然后我试着把Key参数去掉，竟然得到想要的结果，所以我就暂时先这么改了

**Comment by shadowglen** [comment]
你可以自己申请个key呀

**Comment by lordong** [comment]
@shadowglen 我自己没有申请过embedly的key，得知 @netputer 的key都无效了，不用key也能用，所以就没多想了。应该不是每个想部署奶瓶腿的都知道怎么去申请embedly的key，所以很多人都用默认的，然后问题就出来了

**Comment by shadowglen** [comment]
奶瓶腿的github代码里不包含embedly key...

**Comment by netputer** [comment]
其实是有的，当 Key 文本框啥都没填写时，就用预设的也就是自己的 Key 。

争取今天下午 Fix 。

在 2013年6月5日星期三，Shadowglen Elf 写道：

> 奶瓶腿的github代码里不包含embedly key...
> 
> On Jun 5, 2013, at 10:34 AM, lordong <notifications@github.com<javascript:_e({}, 'cvml', 'notifications@github.com');>>
> wrote:
> 
> > @shadowglen 我自己没有申请过embedly的key，得知 @netputer
> > 的key都无效了，不用key也能用，所以就没多想了。应该不是每个想部署奶瓶腿的都知道怎么去申请embedly的key，所以很多人都用默认的，然后问题就出来了
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netputer/netputweets/issues/48#issuecomment-18952380
> .

## 

Sent from Gmail Mobile

**Comment by shadowglen** [comment]
api key有预设 但embedly是没有预设的

**Comment by lordong** [comment]
再下了一版到本地看，原来config-sample.php已经把以前缺省的内容全都改成“putyourinfohere”了，可能我在更新时为了方便直接把以前的config.php拷过来了，所以引起了这个问题。

但 $url = urldecode($url); 似乎要加上，不然没转义回来的URL点图片会导向错误。

**Comment by shadowglen** [comment]
之前的代码里已经把urldecode加上了呀~

**Comment by lordong** [comment]
@shadowglen 明白了，我最新下载的版本是2013-2-27，刚才下载的最新版是2013-4-12的，看到已经改了，应该是我没有更新的问题，就此关贴。
