### ISSUE TITLE
提示：服务器不支持 URL Rewrite ，奶瓶腿将无法使用。

### ISSUE THREAD

**Issue by wujun4code** [netputer/netputweets#52]
我目前也遇到这种情况，我用的是windows azure的云虚拟机，虚拟的ubuntu server 系统。
1.我确定我的apache2 开启了 sudo a2enmod rewrite，我也把配置文件中的改成了AllowOverride All，并且sudo service apache2 restart，但是还是粗线这样的问题……
2.我确定.htaccess文件活着并且存在于根目录下。
2.url rewrite 这个模块是需要服务器本身的机器支持的还是ubuntu 系统支持？本屌是ubuntu新手，见笑见笑。
附上我的网址：http://embr.cloudapp.net/netputweets/setup.php

**Comment by sorz** [comment]
你装的是 Apache，rewrite 功能由 Apache 提供。
应该是要修改 Apache 设置就行了..
（没配过不了解具体

在 2013年10月14日下午9:55，freewing99 notifications@github.com写道：

**Comment by netputer** [comment]
可能是因为根目录的 `.htaccess` 影响。

可以根据 `.htaccess` 的注释修改一下。

**Comment by wujun4code** [comment]
貌似不提出错误了，我手动修改了confi.php，现在出这样的错误：
![error](https://f.cloud.github.com/assets/5119542/1326883/2a0cd030-34e6-11e3-9b9f-17772780a1c8.jpg)
我的配置文件如下：
![oauth](https://f.cloud.github.com/assets/5119542/1326889/3fd9e4b6-34e6-11e3-8cdc-c40d209ffc63.jpg)
ps：附上我的网址：http://embr.cloudapp.net/netputweets/oauth

**Comment by wujun4code** [comment]
成功了！401错误我自行修复了！是我的call back url没设置成功。。
